language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  - mypy rocketchat
